server:
  port: 8401

spring:
  application:
    # 自己服务名称
    name: cloudalibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        # 入住进 Nacos服务注册中心地址
        server-addr: localhost:8848

    web-context-unify: false # controller层的方法对 service层调用不认为是同一个根链路（就是模仿调用其他微服务的控制器）


   # 配置流量监控服务，这个微服务被谁监控
    sentinel:
      transport:
        dashboard: localhost:8080  #配置 Sentinel dashboard 控制台服务地址
        port: 8719 #默认 8719 端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口


      # 配置 sentinel 配置持久化，持久化到 Nacos注册中心
      # 就是使用 nacos 的分布式配置来取代可视化的流控，熔断，热点，授权规则
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848 # nacos 地址
            dataId: ${spring.application.name} # 就是 nacos 配置里面的
            groupId: DEFAULT_GROUP # 就是 nacos 配置里面的
            data-type: json # 就是 nacos 配置里面的
            rule-type: flow # 代表只会持久化流控
        ds2: # 自定义的 key
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade # 代表持久化加上了熔断规则

      #    FLOW("flow", FlowRule.class),
      #    DEGRADE("degrade", DegradeRule.class),
      #    PARAM_FLOW("param-flow", ParamFlowRule.class),
      #    SYSTEM("system", SystemRule.class),
      #    AUTHORITY("authority", AuthorityRule.class),
      #    GW_FLOW("gw-flow", "com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayFlowRule"),
      #    GW_API_GROUP("gw-api-group", "com.alibaba.csp.sentinel.adapter.gateway.common.api.ApiDefinition");









    